name: CMake

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Acquire G++11
      run: sudo apt-get update &&  sudo apt-get install -y g++-11 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 99

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Artefact
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target bundling_target
          
    - name: Release Artefact
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: ${{github.workspace}}/build/libgnutility_bundle.a
        asset_name: x86_64-pc-linux-gnu-utility.a
        prerelease: true
        tag: ${{ github.ref }}
